### ISSUE TITLE
'componentName' is required

### ISSUE THREAD

**Issue by kosuke-zhang** [serverless-tencent/tencent-django#6]
## error info

```
 Error: 'componentName' is required
    at validateAndFormat (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/platform-client-china/src/instance.js:115:11)
    at run (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/platform-client-china/src/instance.js:255:14)
    at Object.deploy (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/platform-client-china/src/instance.js:312:9)
    at ServerlessSDK.deploy (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/platform-client-china/src/index.js:397:27)
    at fn (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/utils.js:592:36)
    at executeGraph (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/utils.js:606:19)
    at executeGraph (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/utils.js:615:10)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/commands-cn/runAll.js:62:36)
    at async Object.module.exports (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/index.js:110:7)

0s › zhangxu › 'componentName' is required
```

## config

```yaml
component: '@serverless/tencent-django'
name: ADreamBackend

org: ADream
app: ADreamAPP
stage: dev


inputs:
  region: ${env:REGION}
  zone: ${env:ZONE}
  functionName: ADreamFun
  djangoProjectName: backend
  code: ./
  functionConf:
    timeout: 10
    memorySize: 256
    environment:
      variables:
        DEBUG: true
        NAME: ${output:${stage}:${app}:ADreamPG.private.dbname}
        USER: ${output:${stage}:${app}:ADreamPG.private.user}
        PASSWORD: ${output:${stage}:${app}:ADreamPG.private.password}
        HOST: ${output:${stage}:${app}:ADreamPG.private.host}
        PORT: ${output:${stage}:${app}:ADreamPG.private.port}
    vpcConfig:
      subnetId: ${output:${stage}:${app}:ADreamVpc.vpcId}
      vpcId: ${output:${stage}:${app}:ADreamVpc.subnetId}
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
```

求助啊，是在没有发现哪里出错了
